version: '3.8'

services:
  chatbot-app:
    build: .
    container_name: langchain_streamlit_chatbot
    ports:
      - "${DOCKER_CHATBOT_PORT_EXTERNAL}:${DOCKER_CHATBOT_PORT_INTERNAL}"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always